apiVersion: v1
kind: Service
metadata:
  name: image-service-service
  labels:
    app: image-service
spec:
  type: LoadBalancer
  selector:
    app: image-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30083