apiVersion: v1
kind: Service
metadata:
  name: message-service-service
  labels:
    app: message-service
spec:
  type: LoadBalancer
  selector:
    app: message-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081